### ISSUE TITLE
Linking against incompatible dylib

### ISSUE THREAD

**Issue by trevor-e** [tamatebako/tebako#211]
I've been trying to compile a Ruby CLI program (using dry-cli) I have to an executable using tebako. I have it successfully generating the binary file, but when I attempt to run it I get this error:
```
➜  cli git:(telkins/cli-deploy) ✗ ./my-cli-output -h
Ignoring io-event-1.7.3 because its extensions are not built. Try: gem pristine io-event --version 1.7.3
Ignoring json-2.8.2 because its extensions are not built. Try: gem pristine json --version 2.8.2
Ignoring racc-1.8.1 because its extensions are not built. Try: gem pristine racc --version 1.8.1
<internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': linked to incompatible /Users/telkins/.rvm/rubies/ruby-3.2.5/lib/libruby.3.2.dylib - /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json/ext/parser.bundle (LoadError)
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:73:in `process_all'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:105:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json/ext.rb:15:in `<module:Ext>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json/ext.rb:8:in `<module:JSON>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json/ext.rb:5:in `<top (required)>'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:73:in `process_all'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:105:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json.rb:586:in `<module:JSON>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/json-2.8.2/lib/json.rb:584:in `<top (required)>'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:73:in `process_all'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:105:in `require'
	from /__tebako_memfs__/local/lib/commands/upload/snapshots/snapshots.rb:2:in `<top (required)>'
	from /__tebako_memfs__/local/lib/my_cli.rb:2:in `require_relative'
	from /__tebako_memfs__/local/lib/my_cli.rb:2:in `<top (required)>'
	from /__tebako_memfs__/local/bin/my_cli.rb:3:in `require_relative'
	from /__tebako_memfs__/local/bin/my_cli.rb:3:in `<main>'
```

I'm compiling it via `PATH="$(brew --prefix bison)/bin:$PATH" tebako press -e bin/my_cli.rb -r . -o my-cli-output -R 3.2.5`. What's interesting is I see 3.2.0 being referenced in the stacktrace, but I'm explicitly compiling with 3.2.5. I also correctly see:
```
➜  cli git:(telkins/cli-deploy) ✗ ruby -v
ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [arm64-darwin24]
```

I'm running on macOS 15.0.1 (24A348) with an M1 chip. I've tried cleaning my build artifacts and running the `gem pristine` commands suggested in the output.

**Comment by maxirmx** [comment]
Hi, @trevor-e 

Thank you for the issue.
Could you please share the output of ```tebako press ...```  command

Thank you

**Comment by maxirmx** [comment]
> I'm compiling it via `PATH="$(brew --prefix bison)/bin:$PATH" tebako press -e bin/my_cli.rb -r . -o my-cli-output -R 3.2.5`. What's interesting is I see 3.2.0 being referenced in the stacktrace, but I'm explicitly compiling with 3.2.5. I also correctly see:

Ruby API version is 3.2.0 for any 3.2.x version, so references to 3.2.0 are normal though confusing

**Comment by maxirmx** [comment]
@trevor-e should you be able to provide more information please feel free to reopen this issue
