### ISSUE TITLE
libui.dylib (no such file) (Fiddle::DLError)

### ISSUE THREAD

**Issue by chip** [tamatebako/tebako#226]
Hi, Thank you for your efforts on this project. I'm running into an issue on an M2 Pro (Ventura 13.4) where running the executable could not find `libui.dylib`. Running `tebako setup` and `tebako press` completed successfully. Please see details in report below.

I'm happy to provide additional info as specified. Any suggestions would be appreciated. Thanks again.

```
λ which ruby
/Users/chip/.rubies/ruby-3.2.6/bin/ruby

λ chruby
   ruby-2.7.7
   ruby-3.0.7
   ruby-3.1.2
   ruby-3.1.4
   ruby-3.2.2
   ruby-3.2.4
 * ruby-3.2.6
   ruby-3.3.0
   ruby-3.3.1
   ruby-3.3.3
   ruby-3.3.6

λ ~/.rubies/ruby-3.2.6/bin/ruby -v
ruby 3.2.6 (2024-10-30 revision 63aeb018eb) [arm64-darwin22]

λ tebako press --root=/Users/chip/code/ruby/pathos_macos --entry-point=/Users/chip/code/ruby/pathos_macos/bin/pathos_macos   
Tebako executable packager version 0.11.0
No prefix specified, using ~/.tebako
-- Absolute path to entry point '/Users/chip/code/ruby/pathos_macos/bin/pathos_macos' will be reduced to 'bin/pathos_macos' relative to '/Users/chip/code/ruby/pathos_macos'
Running tebako press at /Users/chip/.tebako
   Mode:                      'bundle'
   Ruby version:              '3.2.5'
   Project root:              '/Users/chip/code/ruby/pathos_macos/'
   Application entry point:   '/Users/chip/code/ruby/pathos_macos/bin/pathos_macos'
   Package file name:         '/Users/chip/code/ruby/pathos_macos/pathos_macos'
   Loging level:              'error'
   Package working directory: '<Host current directory>'
-- Generating files
   ... tebako-version.h
   ... tebako-fs.cpp
   ... deploy.rb
-- Using brew environment at /opt/homebrew
-- Found bison keg installed by Homebrew at /opt/homebrew/opt/bison
-- Found flex keg installed by Homebrew at /opt/homebrew/opt/flex
-- Found bash keg installed by Homebrew at /opt/homebrew/opt/bash
-- Running tebako press script
Running tebako press script
-- OSTYPE: 'darwin22.6.0'
-- NCORES: 10
Configuration summary:
-- ruby: v3.2.5 at /Users/chip/.tebako/deps/src/_ruby_3.2.5
-- dwarfs with tebako wrapper: @v0.9.2 at /Users/chip/.tebako/deps/src/_dwarfs_wr
-- DATA_SRC_DIR: /Users/chip/.tebako/o/s
-- DATA_PRE_DIR: /Users/chip/.tebako/o/r
-- DATA_BIN_DIR: /Users/chip/.tebako/o/p
-- DATA_BIN_FILE: /Users/chip/.tebako/o/p/fs.bin
-- Target binary directory: /Users/chip/.tebako/o/s/bin
-- Target library directory: /Users/chip/.tebako/o/s/lib
-- Target local directory: /Users/chip/.tebako/o/s/local
-- Target Gem directory:: /Users/chip/.tebako/o/s/lib/ruby/gems/3.2.0
-- FS_MOUNT_POINT: /__tebako_memfs__
-- Building for Win32 Ruby (RB_W32): OFF
-- Removing GLIBC_PRIVATE reference: OFF
-- Not building Ruby extensions: dbm,win32,win32ole,-test-/*
-- Ruby build cflags='-fPIC -I/Users/chip/.tebako/deps/include -I/Users/chip/.gem/ruby/3.2.6/gems/tebako-0.11.0/include -fdeclspec -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/include'
-- Ruby build LDFLAGS='-L/Users/chip/.tebako/deps/lib -L/Users/chip/.tebako/o -L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/opt/zlib/lib  -L/opt/homebrew/lib'
-- openssl Ruby option='--with-openssl-dir=/opt/homebrew/opt/openssl@3'
-- libyaml Ruby option=''
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/chip/.tebako/o
[ 42%] Built target _dwarfs_wr
[ 84%] Built target _ruby_3.2.5
Tebako setup has been verified
[ 84%] Built target setup
-- Running init script
   ... creating packaging environment at /Users/chip/.tebako/o/s
-- Running deploy script
   ... installing tebako-runtime gem
   ... @ /Users/chip/.tebako/o/s/bin/gem install tebako-runtime --no-document --install-dir /Users/chip/.tebako/o/s/lib/ruby/gems/3.2.0
   ... deploying Gemfile
   ... @ /Users/chip/.tebako/o/s/bin/bundle config set --local build.ffi --disable-system-libffi
   ... @ /Users/chip/.tebako/o/s/bin/bundle config set --local build.nokogiri --no-use-system-libraries
   ... @ /Users/chip/.tebako/o/s/bin/bundle config set --local force_ruby_platform false
   *** It may take a long time for a big project. It takes REALLY long time on Windows ***
   ... @ /Users/chip/.tebako/o/s/bin/bundle install --jobs=10
   ... target entry point will be at /__tebako_memfs__/local/bin/pathos_macos
   ... stripping the output
-- Running mkdwarfs script
   ... @ /Users/chip/.tebako/deps/bin/mkdwarfs -o /Users/chip/.tebako/o/p/fs.bin -i /Users/chip/.tebako/o/s --no-progress
[ 84%] Built target packaged_filesystem
[ 94%] Building CXX object CMakeFiles/tebako-fs.dir/Users/chip/.tebako/deps/src/tebako/tebako-fs.cpp.o
[ 94%] Building CXX object CMakeFiles/tebako-fs.dir/src/tebako-main.cpp.o
[100%] Linking CXX static library libtebako-fs.a
[100%] Built target tebako-fs
-- Running finalize script
   ... building tebako package
   ... @ make ruby -j10
   ... @ make -j10
Created tebako package at "/Users/chip/code/ruby/pathos_macos/pathos_macos"
[100%] Built target tebako


λ ./pathos_macos 
/__tebako_memfs__/lib/ruby/3.2.0/fiddle.rb:62:in `initialize': dlopen(/__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/vendor/libui.dylib, 0x0009): tried: '/__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/vendor/libui.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/vendor/libui.dylib' (no such file), '/__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/vendor/libui.dylib' (no such file) (Fiddle::DLError)
	from /__tebako_memfs__/lib/ruby/3.2.0/fiddle.rb:62:in `new'
	from /__tebako_memfs__/lib/ruby/3.2.0/fiddle.rb:62:in `dlopen'
	from /__tebako_memfs__/lib/ruby/3.2.0/fiddle/import.rb:86:in `block in dlload'
	from /__tebako_memfs__/lib/ruby/3.2.0/fiddle/import.rb:77:in `collect'
	from /__tebako_memfs__/lib/ruby/3.2.0/fiddle/import.rb:77:in `dlload'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui/ffi.rb:10:in `<module:FFI>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui/ffi.rb:5:in `<module:LibUI>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui/ffi.rb:4:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui.rb:20:in `require_relative'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui.rb:20:in `<module:LibUI>'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/libui-0.1.2-arm64-darwin/lib/libui.rb:5:in `<top (required)>'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:73:in `process_all'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:105:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/glimmer-dsl-libui-0.12.6/lib/glimmer-dsl-libui.rb:43:in `<top (required)>'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
	from <internal:/__tebako_memfs__/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:73:in `process_all'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/tebako-runtime-0.5.4/lib/tebako-runtime.rb:105:in `require'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/glimmer-dsl-libui-0.12.6/lib/glimmer/launcher.rb:123:in `launch'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/glimmer-dsl-libui-0.12.6/lib/glimmer/launcher.rb:154:in `launch_application'
	from /__tebako_memfs__/lib/ruby/gems/3.2.0/gems/glimmer-dsl-libui-0.12.6/lib/glimmer/launcher.rb:147:in `launch'
	from /__tebako_memfs__/local/bin/pathos_macos:8:in `<main>'
```

**Comment by maxirmx** [comment]
Hi @chip 

Thank you for using tebako

It looks like we need an adapter for fiddle gem similar to [ffi adapter](https://github.com/tamatebako/tebako-runtime/blob/main/lib/tebako-runtime/adapters/ffi.rb)
Please have a look at the  [diagram](https://github.com/tamatebako/tebako-runtime)  if you are interested in details the explanation.

I will do it this year )

----
Implementation note
alias ```Fiddle:dlopen``` at ```/lib/fiddle.rb```
`

**Comment by ronaldtse** [comment]
@maxirmx we should 

1. Provide documentation on how to update gems that utilize low level file system calls that relate with memfs, and also a blog post describing how that works. 
2. Keep an updated list of gems we’ve patched and also a repository of patches for those gems that are “Tebako-ready” so people can also contribute.
