### ISSUE TITLE
A call to timeout during packaging causes SEGFAULT 

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#38]
Similar problems occurs with several gems that use timeout

```
/home/maxirmx/Projects/tebako/output/source_filesystem/lib/ruby/2.7.0/timeout.rb:88: [BUG] Segmentation fault at 0x0000000000000047
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0011 e:000010 CFUNC  :sleep
c:0002 p:0024 s:0006 e:000005 BLOCK  /home/maxirmx/Projects/tebako/output/source_filesystem/lib/ruby/2.7.0/timeout.rb:88 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/maxirmx/Projects/tebako/output/source_filesystem/lib/ruby/2.7.0/timeout.rb:88:in `block (2 levels) in timeout'
/home/maxirmx/Projects/tebako/output/source_filesystem/lib/ruby/2.7.0/timeout.rb:88:in `sleep'
```

**Comment by ronaldtse** [comment]
Line 88 is this:

https://github.com/ruby/ruby/blob/647ee6f091eafcce70ffb75ddf7e121e192ab217/lib/timeout.rb#L88

```rb
  def timeout(sec, klass = nil, message = nil)   #:yield: +sec+
    return yield(sec) if sec == nil or sec.zero?
    message ||= "execution expired".freeze
    from = "from #{caller_locations(1, 1)[0]}" if $DEBUG
    e = Error
    bl = proc do |exception|
      begin
        x = Thread.current
        y = Thread.start {
          Thread.current.name = from
          begin
            sleep sec
          rescue => e
            x.raise e
          else
            x.raise exception, message
          end
        }
        return yield(sec)
# ...
```

It is likely that the call to `sleep` is not returning.

`def sleep` is defined here:
https://github.com/ruby/ruby/blob/d09cb64ae5c618f1cb2d90c544b7e0bc55ebb003/lib/mutex_m.rb#L102-L105
```rb
  # See Thread::Mutex#sleep
  def sleep(timeout = nil)
    @_mutex.sleep(timeout)
  end
```

Not sure where this goes...
Which is Thread::Mutex.sleep, defined in `ruby/thread_sync.c`:

https://github.com/ruby/ruby/blob/5a048829a488bb1cb4b0e77b3d46a1920ad92136/thread_sync.c#L529-L586

Which calls `rb_fiber_scheduler_kernel_sleep` in `scheduler.c`:

https://github.com/ruby/ruby/blob/81d0ce7e97af74a2086e143f9e349ee519bd1c4d/scheduler.c#L159-L164

```c
VALUE
rb_fiber_scheduler_kernel_sleep(VALUE scheduler, VALUE timeout)
{
    return rb_funcall(scheduler, id_kernel_sleep, 1, timeout);
}
```

Which calls `rb_funcall` defined in `ruby.h`:

https://github.com/ruby/ruby/blob/cb4e2cb55a59833fc4f1f6db2f3082d1ffcafc80/include/ruby/ruby.h#L288-L297

```c
# define rb_funcall(recv, mid, argc, ...) \
__extension__({ \
	const int rb_funcall_argc = (argc); \
	const VALUE rb_funcall_args[] = {__VA_ARGS__}; \
	const int rb_funcall_nargs = \
	    (int)(sizeof(rb_funcall_args) / sizeof(VALUE)); \
        rb_funcallv(recv, mid, \
	    rb_varargs_argc_check(rb_funcall_argc, rb_funcall_nargs), \
	    rb_funcall_nargs ? rb_funcall_args : NULL); \
    })
```

Which calls `rb_funcallv` defined in `eval.h`:
https://github.com/ruby/ruby/blob/cb4e2cb55a59833fc4f1f6db2f3082d1ffcafc80/include/ruby/internal/eval.h#L106-L118

```c
/**
 * Identical  to rb_funcall(),  except it  takes the  method arguments  as a  C
 * array.
 *
 * @param[in,out]  recv               Receiver of the method.
 * @param[in]      mid                Name of the method to call.
 * @param[in]      argc               Number of arguments.
 * @param[in]      argv               Arbitrary number of method arguments.
 * @exception      rb_eNoMethodError  No such method.
 * @exception      rb_eException      Any exceptions happen inside.
 * @return         What the method evaluates to.
 */
VALUE rb_funcallv(VALUE recv, ID mid, int argc, const VALUE *argv);
```

So `rb_fiber_scheduler_kernel_sleep` is basically passing a call to the scheduler.

In `scheduler.c` we see that:
```c
/*...*/
static ID id_kernel_sleep;
/*...*/
    id_kernel_sleep = rb_intern_const("kernel_sleep");
```

In `cont.c` we see that `kernel_sleep` is a Scheduler method:

https://github.com/ruby/ruby/blob/90f2ab9d62860d7b3413fb363403c1d16b4a860e/cont.c#L3127

```c
    rb_define_method(rb_cFiberScheduler, "kernel_sleep", rb_fiber_scheduler_interface_kernel_sleep, 0);
```

This goes back to the Ruby side:
https://github.com/ruby/ruby/blob/a88b19d3d08447eeb7045621f02a844173d64203/test/fiber/scheduler.rb#L197-L204
```ruby
  # Used for Kernel#sleep and Thread::Mutex#sleep
  def kernel_sleep(duration = nil)
    # $stderr.puts [__method__, duration, Fiber.current].inspect

    self.block(:sleep, duration)

    return true
  end
```

`Scheduler#block` is defined in the same file:
https://github.com/ruby/ruby/blob/a88b19d3d08447eeb7045621f02a844173d64203/test/fiber/scheduler.rb#L208

```ruby
  def block(blocker, timeout = nil)
    # $stderr.puts [__method__, blocker, timeout].inspect

    if timeout
      @waiting[Fiber.current] = current_time + timeout
      begin
        Fiber.yield
      ensure
        # Remove from @waiting in the case #unblock was called before the timeout expired:
        @waiting.delete(Fiber.current)
      end
    else
      @blocking += 1
      begin
        Fiber.yield
      ensure
        @blocking -= 1
      end
    end
  end
```

So it calls `Fiber.yield`. It is defined as `rb_fiber_yield`:
https://github.com/ruby/ruby/blob/90f2ab9d62860d7b3413fb363403c1d16b4a860e/cont.c#L2454-L2458

```
VALUE
rb_fiber_yield(int argc, const VALUE *argv)
{
    return fiber_switch(return_fiber(false), argc, argv, RB_NO_KEYWORDS, NULL, true);
}
```

And `fiber_switch` is in the same file, very long...:
https://github.com/ruby/ruby/blob/90f2ab9d62860d7b3413fb363403c1d16b4a860e/cont.c#L2231-L2321

Which basically runs a fiber stack. The important call seems to be `EXEC_EVENT_HOOK` which is eventually a macro to `rb_exec_event_hooks` in `ruby/vm_core.h`.

https://github.com/ruby/ruby/blob/f943264565f3072a30616fa93ffa3da3790294b0/vm_core.h#L2022-L2067

And the function is defined in `ruby/vm_trace.c`:

https://github.com/ruby/ruby/blob/f5d20411386ff2552ff27661387ddc4bae1ebc30/vm_trace.c#L378-L429

**Comment by ronaldtse** [comment]
Given it is a segfault perhaps it is some `Thread` problem pointing to a wrong memory location...

**Comment by maxirmx** [comment]
I found that this issue is related to ruby static build and is not related to packaging.
If I link it as dynamic executable it does not happen.

As far as I understood static builds are not officially supported after 2.5 and I am using 2.7 so probably nobode have tested it static build.

**Comment by maxirmx** [comment]
Atatched there are linker log and run-time stack trace
[Linker log](https://github.com/tamatebako/tebako/files/7607452/tebako-issue-38-0.txt)
[Run-time stack trace](https://github.com/tamatebako/tebako/files/7607453/tebako-issue-38-1.txt)
](url)

Important line are marked as **=== Error location ======>**

As far as I know such warning as in linker log usually are not fatal, not even errors
However, socket extension fails

**Comment by maxirmx** [comment]
This issue is related to #42 and shall be discussed in broader context
