### ISSUE TITLE
Tebako fails to package libmspack gem

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#68]
tebako-packaged metanorma bundle is failing at MacOS because of some issue related to libmspack
Of course it is not very clear, since it crashes on 10.15/x86 (GHA), returns reasonable error on arm86(local), but apparently works with ruby-packer.

This is the output I have with metanorma

```
traceback (most recent call last):
	2: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	1: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- isodoc (LoadError)
	9: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	8: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	7: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	6: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	5: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc.rb:20:in `<top (required)>'
	4: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	3: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	2: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/xslfo_convert.rb:1:in `<top (required)>'
	1: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require': cannot load such file -- metanorma (LoadError)
	35: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	34: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	33: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	32: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	31: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc.rb:20:in `<top (required)>'
	30: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	29: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	28: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/xslfo_convert.rb:1:in `<top (required)>'
	27: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	26: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	25: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	24: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma.rb:11:in `<top (required)>'
	23: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	22: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	21: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:5:in `<top (required)>'
	20: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	19: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	18: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist.rb:11:in `<top (required)>'
	17: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	16: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	15: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist/font.rb:1:in `<top (required)>'
	14: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	13: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	12: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist/font_installer.rb:2:in `<top (required)>'
	11: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	10: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 9: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `<top (required)>'
	 8: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `require_relative'
	 7: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:2:in `<top (required)>'
	 6: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:2:in `require_relative'
	 5: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors/cab_extractor.rb:1:in `<top (required)>'
	 4: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 3: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 2: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:16:in `<top (required)>'
	 1: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:18:in `<module:LibMsPack>'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/ffi-compiler2-2.0.1/lib/ffi-compiler/loader.rb:25:in `find': cannot find 'libmspack' library (LoadError)```

**Comment by maxirmx** [comment]
This is distilled output from simple test
```
	2: from /__tebako_memfs__/local/gems-libmspack.rb:1:in `<main>'
	1: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- libmspack (LoadError)
	6: from /__tebako_memfs__/local/gems-libmspack.rb:1:in `<main>'
	5: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	4: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	3: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	2: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:16:in `<top (required)>'
	1: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:18:in `<module:LibMsPack>'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/ffi-compiler2-2.0.1/lib/ffi-compiler/loader.rb:25:in `find': cannot find 'libmspack' library (LoadError)
```

```
require 'libmspack'

LibMsPack
puts "Hello! libmspack welcomes you to the magic world of ruby gems."```

**Comment by maxirmx** [comment]
This issue is somehow related to https://github.com/metanorma/packed-mn/issues/142

**Comment by ronaldtse** [comment]
@maxirmx the issue is that the `libmspack` gem uses `ffi-compiler` which builds a wrong path prefix for the library (see https://github.com/metanorma/packed-mn/issues/142#issuecomment-998469487).

There are two options:
1. We fix `libmspack` and `ffi-compiler` gems to use the correct library name during build time and run time.
2. We hack `libmspack` in the packed-mn metanorma entry file to use the correct library name.

@alexeymorozov perhaps 2 is the easiest way to move ahead?
